services:
  - type: web
    name: todo-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: APP_URL
        value: https://gogoyun.github.io/todo/  # 請替換為你的前端 URL
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false  # 請在 Render 控制台手動設定
      - key: SMTP_PASSWORD
        sync: false  # 請在 Render 控制台手動設定
      - key: SMTP_FROM_EMAIL
        sync: false  # 請在 Render 控制台手動設定

databases:
  - name: todo-postgres
    databaseName: todo_db
    user: todo_user 